bandstand-test-runner:
  owner: ktech-developer-platform
  env: test
  business: ktech

  commonEnvFrom:
    - configMapRef:
        name: shared-config-map

  testRuns:
    - name: test-suite-1
      envFrom:
        - configMapRef:
            name: test-run-config-map


