bandstand-triggered-job:
  owner: ktech-developer-platform
  env: test
  business: ktech

  secrets:
    - name: my-first-secret
      secret: my-secret-name
      prefix: my-prefix
      optional: true
    - name: my-second-secret
      secret: my-other-secret-name

  envFrom:
    - configMapRef:
        name: shared-config-map
