bandstand-web-service:
  owner: ktech-developer-platform
  env: test
  business: ktech
  imageName: my-custom-image

  ingress:
    enabled: true

global:
  dockerRegistry: 067805054192.dkr.ecr.eu-west-1.amazonaws.com
