{{- if (.Values.volume).persistent }}
{{- $relName := include "bandstand-headless-service.fullname" $ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-headless-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.volume.storageClass | default "general-storage" }}
  resources:
    requests:
      storage: {{ (.Values.volume).persistent }}
{{- end -}}
