{{- $relName := include "bandstand-headless-service.fullname" $ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-headless-service.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account | toYaml }}:role/{{ $relName }}
