bandstand-headless-service:
  owner: ktech-developer-platform
  env: test
  business: ktech

  secrets:
    - name: my-first-secret
      secret: my-secret-name
      prefix: my-prefix
      optional: true
    - name: my-second-secret
      secret: my-other-secret-name
    - name: my-templated-secret
      secret: my-{{.Values.env}}-secret-name
