bandstand-web-service:
  owner: ktech-developer-platform
  env: test
  business: ktech

  ingress:
    enabled: true
    domain: ktech.com
    visibility: cluster
    authenticationBackend: authentication
