{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: {{ $relName }}-{{ .Values.global.env }}
  labels: {{- include "bandstand-confluent-connector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ - include "bandstand-confluent-connector.selectorLabels" . | nindent 6 }}
  name: {{ $relName }}-{{ .Values.global.env }}
  class: {{ .Values.config.class | default "io.confluent.connect.jdbc.JdbcSourceConnector" }}
  taskMax: {{ .Values.config.taskMax | default 1 }}
  connectClusterRef:
    name: {{ .Values.config.connectClusterName | default "confluent-connect" }}
    namespace: {{ .Values.global.namespace }}
  configs:
    connection.url: "{{ tpl .Values.config.connectionUrl . }}"
    connection.user: "{{ tpl .Values.config.connectionUser . }}"
    connection.password: "{{ tpl .Values.config.connectionPassword . }}"
    config.providers: "secretsManager"
    config.providers.secretsManager.class: "io.confluent.csid.config.provider.aws.SecretsManagerConfigProvider"
    config.providers.secretsManager.param.aws.region: "eu-west-1"
    db.timezone: "UTC"
    value.converter.schema.registry.url: "{{ .Values.config.schemaUrl }}"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: "false"
    value.converter.basic.auth.credentials.source: "USER_INFO"
    value.converter.schema.registry.basic.auth.user.info: "{{ tpl .Values.config.schemaAuthUserInfo . }}"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
