bandstand-headless-service:
  owner: ktech-developer-platform
  env: test
  business: ktech

livenessProbe:
  exec:
    command:
      - ./livenessProbe.sh
  initialDelaySeconds: 5
  periodSeconds: 30

startupProbe:
  exec:
    command:
      - ./startupProbe.sh
  periodSeconds: 10
