{{- define "bandstand-cron-job.configmap" -}}
{{- if .Values.properties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "bandstand-cron-job.labels" . | nindent 4 }}
data:
  app.properties: {{- .Values.properties | toYaml | indent 2 }}
{{- end }}
{{- end -}}
