{{- if and .Values.s3Volumes (gt (len .Values.s3Volumes) 0) }}
{{- range $volume := .Values.s3Volumes }}
{{- $relName := printf "%s-%s" .Release.Name $volume.name }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" $relName }}
  labels:
    {{- include "bandstand-cron-job.labels" $ | nindent 4 }}
spec:
  capacity:
    storage: {{ $volume.persistent | default "5Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.aws.com
    volumeHandle: {{ $volume.volumeHandle | default (print "s3-" $relName "-volume") }}
    volumeAttributes:
      bucketName: {{ $volume.bucketName }}
      authenticationSource: pod
  {{- if $volume.prefix }}
  mountOptions:
    - prefix {{ $volume.prefix }}
  {{- end }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ $volume.pvcName | default $relName }}
---
{{- end }}
{{- end }}
