{{- if and .Values.s3Volumes (gt (len .Values.s3Volumes) 0) }}
{{- range $volume := .Values.s3Volumes }}
{{- $relName := printf "%s-%s" .Release.Name $volume.name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" $relName }}
  labels:
    {{- include "bandstand-cron-job.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.persistent | default "5Gi" }}
---
{{- end }}
{{- end }}
