{{- define "service-library.ingress" -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "service-library.labels" . | nindent 4 }}
  annotations:
    bandstand.ktech.com/service-visibility: private
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
      - "{{ .Release.Name }}.{{ .Values.env }}.{{ .Values.ingress.domain }}"
  rules:
    - host: "{{ .Release.Name }}.{{ .Values.env }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
{{- end }}
{{- end }}
