{{- define "service-library.serviceaccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "service-library.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account | toYaml }}:role/{{ .Release.Name }}
{{- end -}}
