bandstand-web-service:
  owner: ktech-developer-platform
  env: test
  business: ktech

  ingress:
    enabled: false

  secrets:
    - name: my-first-secret
      secret: my-secret-name
      prefix: my-prefix
      optional: true
    - name: my-second-secret
      secret: my-other-secret-name

  test:
    secrets:
      - name: my-first-test-secret
        secret: my-secret-name
        prefix: my-prefix
        optional: true
      - name: my-second-test-secret
        secret: my-other-secret-name
