bandstand-confluent-connect:
  owner: ktech-developer-platform
  bootstrapEndpoint: bootstrap-server:9093
  schemaRegistryUrl: https://schema-reg.com/

  connectors:
    - name: source
      class: "io.confluent.connect.jdbc.JdbcSourceConnector"
      taskMax: 3
      config:
        connection.url: sourcedburl
        connection.user: sourcedbuser
        connection.password: sourcedbpassword
    - name: sink
      class: "io.confluent.connect.jdbc.JdbcSinkConnector"
      config:
        connection.url: sinkdburl
        connection.user: sinkdbuser
        connection.password: sinkdbpassword
