bandstand-confluent-connect:
  owner: ktech-developer-platform

  connectors:
    - name: source
      class: "io.confluent.connect.jdbc.JdbcSourceConnector"
      taskMax: 3
      config:
        connection.url: sourcedburl
        connection.user: sourcedbuser
        connection.password: sourcedbpassword
    - name: sink
      class: "io.confluent.connect.jdbc.JdbcSinkConnector"
      config:
        connection.url: sinkdburl
        connection.user: sinkdbuser
        connection.password: sinkdbpassword
