{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-confluent-connect.labels" . | nindent 4 }}
spec:
  replicas: 1
  image:
    application: {{ .Values.applicationImage }}
    init: {{ .Values.initImage }}
    pullPolicy: Always
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
        {{- range $k, $v := .Values.connectPlugins }}
          - name: {{ (split "/" $k)._1 }}
            owner: {{ (split "/" $k)._0 }}
            version: {{ $v }}
        {{- end }}
  podTemplate:
    annotations:
      ad.datadoghq.com/royid-connect-svc.checks: |
        {
          "confluent_platform": {
            "init_config": {
              "is_jmx": true,
              "collect_default_metrics": false,
              "conf": [
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connector-task-metrics",
                    "bean_regex": "kafka.connect:type=connector-task-metrics,connector=.*,task=.*",
                    "attribute": {
                      "status": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.connector_metrics.status",
                        "values": {
                          "running": 0,
                          "paused": 1,
                          "failed": 2,
                          "destroyed": 3,
                          "unassigned": -1
                        }
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connect-worker-metrics",
                    "bean_regex": "kafka.connect:type=connect-worker-metrics,connector=.*",
                    "attribute": {
                      "connector-total-task-count": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.worker.connector-total-task-count"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connect-worker-metrics",
                    "bean_regex": "kafka.connect:type=connect-worker-metrics,connector=.*",
                    "attribute": {
                      "connector-running-task-count": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.worker.connector-running-task-count"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connect-worker-metrics",
                    "bean": "kafka.connect:type=connect-worker-metrics",
                    "attribute": {
                      "connector-count": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.worker.connector-count"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connect-metrics",
                    "bean_regex": "kafka.connect:type=connect-metrics,client-id=.*",
                    "attribute": {
                      "incoming_byte_rate": {
                        "alias": "confluent.kafka.connect.connect_metrics.incoming_byte_rate"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "connect-metrics",
                    "bean_regex": "kafka.connect:type=connect-metrics,client-id=.*",
                    "attribute": {
                      "outgoing-byte-rate": {
                        "alias": "confluent.kafka.connect.connect_metrics.outgoing_byte_rate"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "source-task-metrics",
                    "bean_regex": "kafka.connect:type=source-task-metrics,connector=.*,task=.*",
                    "attribute": {
                      "source-record-write-total": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.source_task.source-record-write-total"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "source-task-metrics",
                    "bean_regex": "kafka.connect:type=source-task-metrics,connector=.*,task=.*",
                    "attribute": {
                      "source-record-write-rate": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.source_task.source-record-write-rate"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "source-task-metrics",
                    "bean_regex": "kafka.connect:type=source-task-metrics,connector=.*,task=.*",
                    "attribute": {
                      "source-record-poll-total": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.source_task.source-record-poll-total"
                      }
                    }
                  }
                },
                {
                  "include": {
                    "domain": "kafka.connect",
                    "type": "source-task-metrics",
                    "bean_regex": "kafka.connect:type=source-task-metrics,connector=.*,task=.*",
                    "attribute": {
                      "source-record-poll-rate": {
                        "metric_type": "gauge",
                        "alias": "confluent.kafka.connect.source_task.source-record-poll-rate"
                      }
                    }
                  }
                }
              ]
            },
            "instances": [{
              "host": "%%host%%",
              "port": "7203"
            }]
          }
        }
    serviceAccountName: {{ $relName }}
    resources:
      requests:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
        ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
      limits:
        {{- if .Values.enforceCpuLimits }}
        cpu: {{ .Values.resources.requests.cpu }}
        {{- end }}
        memory: {{ .Values.resources.requests.memory }}
        ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.bootstrapEndpoint }}
      authentication:
        type: plain
        jaasConfig:
          secretRef: {{ $relName }}
      tls:
        enabled: true
        ignoreTrustStoreConfig: true
    schemaRegistry:
      url: {{ .Values.schemaRegistryUrl }}
      authentication:
        type: basic
        basic:
          secretRef: {{ $relName }}
