apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $relName }}-schema
  annotations:
    force-sync: '{{ now | unixEpoch }}'
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target: {}
  data:
    - secretKey: basic.txt
      remoteRef:
        key: /confluent/{{ .Values.global.business }}-{{ .Values.global.env }}/schema-registry
        property: basic.txt
