apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $relName }}-kafka
  annotations:
    force-sync: '{{ now | unixEpoch }}'
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target: {}
  data:
    - secretKey: plain.txt
      remoteRef:
        key: /confluent/{{ .Values.global.business }}-{{ .Values.global.env }}/service-account/{{ $relName }}
        property: plain.txt
