{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-confluent-connect.labels" . | nindent 4 }}
  annotations:
    force-sync: '{{ now | unixEpoch }}'
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target: {}
  data:
    - secretKey: plain.txt
      remoteRef:
        key: /confluent/{{ .Values.global.business }}-{{ .Values.global.env }}/service-account/{{ $relName }}
        property: plain.txt
    - secretKey: basic.txt
      remoteRef:
        key: /confluent/{{ .Values.global.business }}-{{ .Values.global.env }}/schema-registry
        property: basic.txt
