{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-confluent-connect.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account | toYaml }}:role/{{ $relName }}
