bandstand-web-service:
  owner: ktech-developer-platform
  env: test
  business: ktech

  ingress:
    enabled: false

test:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
      ephemeral-storage: 128Mi
