aliased-chart:
  owner: ktech-developer-platform
  env: test
  business: ktech

  ingress:
    enabled: false

  hpa:
    enabled: false

  advancedScaling:
    enabled: true
    idleReplicas: 0
    minReplicas: 2
    maxReplicas: 10

    scalers:
      - type: cpu
        threshold: 50
      - type: memory
        threshold: 50
      - type: cron
        desiredReplicas: 1
        start: 0 7 * * MON-FRI
        end: 0 19 * * MON-FRI
      - type: msk
        topic: event.msk.reference.dummy
        consumerGroup: keda-consumer
        bootstrapServersEnvVar: MSK_BOOTSTRAP_SERVERS # optional - defaults to KAFKA_BROKERS
        lagThreshold: 100
        tls: enable
      - type: confluent
        topic: event.confluent.reference.dummy
        consumerGroup: keda-consumer
        bootstrapServersEnvVar: CONFLUENT_BOOTSTRAP_SERVERS # optional - defaults to KAFKA_BROKERS
        lagThreshold: 100
