apiVersion: v2
name: ${{values.component}}
version: 1.0.0
description: Chart for deploying ${{values.component}}
type: application
sources:
  - https://github.com/ktech-org/${{values.component}}
maintainers:
  - name: ${{values.owner}}
