{{- define "service-library.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "service-library.labels" . | nindent 4 }}
data:
  app.properties: {{ .Values.properties | toYaml | indent 2 }}
{{- end -}}
