{{- define "bandstand-web-service.configmap" -}}
{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-web-service.labels" . | nindent 4 }}
{{- if or .Values.properties .Values.envproperties }}
data:
  app.properties: |
    {{- if .Values.properties }}
      {{-  .Values.properties | toYaml | replace "|"  "" | indent 2  }}
    {{- end }}
    {{- if .Values.envproperties }}
      {{-  .Values.envproperties | toYaml | replace "|"  "" | indent 2 }}
    {{- end }}
{{- end }}
{{- end -}}
