{{- define "bandstand-web-service.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "bandstand-web-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "bandstand-web-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels: {{- include "bandstand-web-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: 067805054192.dkr.ecr.eu-west-1.amazonaws.com/{{ .Release.Name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
              readOnly: false
            - name: config
              mountPath: "/etc/{{ .Release.Name }}/config"
              readOnly: true
          resources:
            requests:
              cpu: {{ (.Values.resources).requests.cpu | default "250m" }}
              memory: {{ (.Values.resources).requests.memory | default "256Mi" }}
            limits:
              cpu: {{ (.Values.resources).limits.cpu | default "500m" }}
              memory: {{ (.Values.resources).limits.memory | default "512Mi" }}
          livenessProbe:
            httpGet:
              path: {{ (.Values.livenessProbe).path | default "/" }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ (.Values.readinessProbe).path | default "/" }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: ENV
              value: {{ .Values.env }}
            - name: VERSION
              value: {{ .Values.image.tag }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- range $.Values.additionalEnvVars}}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
            items:
              - key: "app.properties"
                path: "app.properties"
        - name: tmp-dir
          emptyDir: {}
      securityContext:
        runAsUser: 1000
{{- end -}}
