{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
{{- range $.Values.additionalDomains -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $relName }}
spec:
  commonName: {{ . }}
  dnsNames:
    - "*.{{ . }}"
  duration: 720h
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: cluster-issuer
  renewBefore: 24h
  secretName: additional-domain-cert
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048
{{- end -}}
