{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
{{- range $i, $domain := .Values.additionalDomains -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $relName }}-{{ $i }}
spec:
  commonName: {{ $domain }}
  dnsNames:
    - "*.{{ $domain }}"
  duration: 24h
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: cluster-issuer
  renewBefore: 2h
  secretName: additional-domain-cert
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048
---
{{ end -}}
