{{- range .Values.secrets }}
{{- $secretHash := sha256sum .secret | substr 0 6 }}
{{- $secretName := list $.Release.Name $.Values.nameSuffix .name $secretHash | join "-" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  annotations:
    force-sync: '{{ now | unixEpoch }}'
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target: {}
  dataFrom:
    - extract:
        key: {{ tpl .secret $ }}
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9]"
            target: "_"
        {{- if .upperCaseKeys }}
        - transform:
            template: {{`'{{ .value | upper }}'`}}
        {{- end}}
---
{{- end }}
