{{- if ne ((.Values.hpa).enabled) false }}
{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-web-service.labels" . | nindent 4 }}
spec:
  minReplicas: {{ ((.Values.hpa).minReplicas) | default 1 }}
  maxReplicas: {{ ((.Values.hpa).maxReplicas) | default 3 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $relName }}
  targetCPUUtilizationPercentage: {{ ((.Values.hpa).averageCpuUtilization) | default 50 }}
{{- end }}
