{{- $relName := .Release.Name -}}
{{- if .Values.nameSuffix }}
{{- $relName = print .Release.Name "-" .Values.nameSuffix }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $relName }}
spec:
  selector: {{- include "bandstand-web-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8080
