{{- $relName := include "bandstand-web-service.fullname" $ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $relName }}
  labels: {{- include "bandstand-web-service.labels" . | nindent 4 }}
spec:
  selector: {{- include "bandstand-web-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8080
