# name: Deploy Environment

# run-name: Manually ${{ (inputs.destroy) && 'Destroy' || 'Deploy to' }} ${{ inputs.business }}-${{ inputs.environment }}

# on:
#   workflow_call:
#     inputs:
#       business:
#         type: string
#         required: true
#       environment:
#         type: string
#         required: true
#       image-tag:
#         description: Global image tag
#         type: string
#         required: false
#       destroy:
#         description: Flag to destroy environments
#         type: boolean
#         default: false
#   workflow_dispatch:
#     inputs:
#       business:
#         description: Business to deploy to
#         type: choice
#         options:
#           - ktech
#           - default
#         required: true
#       environment:
#         description: Environment to deploy to
#         type: choice
#         options:
#           - test
#         required: true
#       image-tag:
#         description: Image tag/version to deploy
#         type: string
#         required: false
#       destroy:
#         description: Destroy environment?
#         type: boolean
#         default: false
#         required: true

# concurrency:
#   group: ${{ inputs.business }}-${{ inputs.environment }}
#   cancel-in-progress: false

# jobs:  
#   bandstand-chart:
#     uses: ktech-org/actions/.github/workflows/bandstand-deploy.yaml@v0
#     secrets: inherit   
#     with:
#       chart: chart/     
#       namespace: lab
#       values: ${{ matrix.chart }}/values.yaml
#       dry-run: false
#       business: ${{ inputs.business }}
#       environment: ${{ inputs.environment }}
#       destroy: ${{ inputs.destroy }}
